# Generated by Django 2.0.5 on 2018-05-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaning_logs', '0003_entry_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
